name: Configure a QT project

needs:
  packages:
    - cmake
    - ninja
    - qt6-qtbase-dev #Qt6Config
    - libxkbcommon-dev #Qt6Gui
    - libglvnd-dev

inputs:
  output-dir:
    description: |
      The output directory for the QT build.
    default: output

  opts:
    description: |
      Compile options for the QT build.

pipeline:
  - runs: |
      cmake -B ${{inputs.output-dir}} -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DINSTALL_BINDIR=lib/qt6/bin \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
        -DINSTALL_BINDIR=lib/qt6/bin \
        -DINSTALL_PUBLICBINDIR=usr/bin \
        -DINSTALL_DOCDIR=share/doc/qt6 \
        -DINSTALL_ARCHDATADIR=lib/qt6 \
        -DINSTALL_DATADIR=share/qt6 \
        -DINSTALL_INCLUDEDIR=include/qt6 \
        -DINSTALL_MKSPECSDIR=lib/qt6/mkspecs \
        -DINSTALL_EXAMPLESDIR=share/doc/qt6/examples \
        -DQT_FEATURE_journald=OFF \
        -DQT_FEATURE_reduce_relocations=OFF \
        -DQT_FEATURE_wayland=ON \
        -DQT_FEATURE_vulkan=ON \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_INSTALL_EXAMPLES_SOURCES=OFF
        ${{inputs.opts}}

