package:
  name: appmenu-gtk-module
  version: 25.04
  epoch: 0
  description: Global Menu for Vala Panel (and xfce4-panel and mate-panel)
  copyright:
    - license: LGPL-3.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - vala
      - gtk-3-dev
      - cmake
      - libwnck-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/vala-panel-project/vala-panel-appmenu/
      tag: ${{package.version}}
      expected-commit: 8c8e788bf04c8c2911b72a24e3b79842d5b2b286

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 230554

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
