package:
  name: eglexternalplatform
  version: "1.2"
  epoch: 0
  description:  The EGL External Platform interface 
  copyright:
    - license: MIT

    # TODO: noarch

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/eglexternalplatform
      tag: ${{package.version}}
      expected-commit: 3875a836d5e30f01edd31b7318c52f171516224c

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 12877

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
