package:
  name: gpgmepp
  version: "2.0.0"
  epoch: 1
  description: GPGME CPP bindings
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - coreutils
      - libgpg-error-dev
      - gpgme-dev

  environment:
    top_builddir: "/home/build/"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 301d39f8b97a79369292280e201e45f472d71e91
      repository: git://git.gnupg.org/gpgmepp.git
      tag: ${{package.name}}-${{package.version}}

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 378536

test:
  pipeline:
    - uses: test/tw/ldd-check
