package:
  name: kdecoration
  version: "6.4.90"
  epoch: 0
  description: Plugin-based library to create window decorations
  copyright:
    - license: LGPL-3.0-only AND LGPL-2.1-only AND CC0-1.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-ki18n-dev
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: febdb3cfac371ae4b4e6823e72a6b716971d436a
      repository: https://invent.kde.org/plasma/kdecoration
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
