package:
  name: kf6-syndication
  version: "6.18.0"
  epoch: 0
  description: Syndication Library
  copyright:
    - license: BSD-2-Clause AND CC0-1.0 AND GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-kcodecs-dev
      - qt6-qtbase-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8bc05c864607dd09c6abf560520a009b54fffa11
      repository: https://invent.kde.org/frameworks/syndication
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

