package:
  name: kf6-kitemviews
  version: "6.18.0"
  epoch: 0
  description: KItemViews
  copyright:
    - license: CC0-1.0 AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qttools-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e671da66133e3b7d129550717b1fcde785c0a284
      repository: https://invent.kde.org/frameworks/kitemviews
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

