package:
  name: kf6-sonnet
  version: "6.18.0"
  epoch: 0
  description: 
  copyright:
    - license: 

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - hunspell-dev
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qttools-dev
      - vulkan-headers
      #- TODO: voikko for finnish stuf, apsell, hspell

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d711f6604fd881b46ca4b50568104683b457a22a
      repository: https://invent.kde.org/frameworks/sonnet
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

