package:
  name: kf6-kunitconversion
  version: "6.18.0"
  epoch: 0
  description: KUnitConversion
  copyright:
    - license: CC0-1.0 AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - qt6-qtbase-dev
      - kf6-ki18n-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 
      repository: https://invent.kde.org/frameworks/kunitconversion
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/ \
        -DBUILD_PYTHON_BINDINGS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

