package:
  name: kf6-ksvg
  version: "6.18.0"
  epoch: 0
  description: Components for handling SVGs
  copyright:
    - license: CC0-1.0 AND GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-karchive-dev
      - kf6-kcolorscheme-dev
      - kf6-kconfig-dev
      - kf6-kcoreaddons-dev
      - kf6-kguiaddons-dev
      - kf6-kirigami-dev
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtsvg-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ce18719b2dc94bf23526a8e06581b4dc25e0a2d5
      repository: https://invent.kde.org/frameworks/ksvg
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

