package:
  name: kf6-kcoreaddons
  version: "6.18.0"
  epoch: 0
  description: KCoreAddons
  copyright:
    - license: BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-2.0-or-later AND MPL-1.1 AND LGPL-2.0-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LGPL-2.1-only WITH Qt-LGPL-exception-1.1

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qttools-dev
      - systemd-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8d0bda07610e60e8cbdf61ea79b9e09978f44555
      repository: https://invent.kde.org/frameworks/kcoreaddons
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/ \
        -DBUILD_PYTHON_BINDINGS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

