package:
  name: kf6-kpackage
  version: "6.18.0"
  epoch: 0
  description: This framework lets applications manage user installable packages of non-binary assets
  copyright:
    - license: CC0-1.0 AND GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-karchive-dev
      - kf6-kcoreaddons-dev
      - kf6-kdoctools-dev
      - kf6-ki18n-dev
      - qt6-qtbase-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a30f9014184b38cb4763447dfc6aff80c5845dbd
      repository: https://invent.kde.org/frameworks/kpackage
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

