package:
  name: kf6-kquickcharts
  version: "6.18.0"
  epoch: 0
  description: A QtQuick plugin providing high-performance charts.
  copyright:
    - license: BSD-2-Clause AND CC0-1.0 AND LGPL-2.1-only AND LGPL-3.0-only AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtshadertools-dev
      - qt6-qttools-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9c9a322cd035d85d2da74159c3f4eda8a2ab1511
      repository: https://invent.kde.org/frameworks/kquickcharts
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

