package:
  name: kf6-karchive
  version: "6.18.0"
  epoch: 0
  description: Qt addon providing access to numerous types of archives
  copyright:
    - license: LGPL-2.0-or-later AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND CC-BY-SA-4.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - extra-cmake-modules
      - libglvnd-dev
      - openssl-dev
      - qt6-qtbase-dev
      - qt6-qttools-dev
      - xz-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e54009eecbea39c4c0b8eb540160960183c30702
      repository: https://invent.kde.org/frameworks/karchive
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

