package:
  name: kf6-kirigami
  version: "6.18.0"
  epoch: 0
  description: A QtQuick based components set
  copyright:
    - license: BSD-3-Clause AND CC0-1.0 AND FSFAP AND GPL-2.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND (LGPL-2.1-only OR LGPL-3.0-only) AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtshadertools-dev
      - qt6-qtsvg-dev
      - qt6-qttools-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c93b3770d8c980f7eb0c67ca3a2e858d610649b5
      repository: https://invent.kde.org/frameworks/kirigami
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

