package:
  name: kf6-kdeclarative
  version: "6.18.0"
  epoch: 0
  description: KDeclarative
  copyright:
    - license: CC0-1.0 AND GPL-2.0-only AND GPL-3.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later AND (GPL-2.0-only OR GPL-3.0-only) AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-kconfig-dev
      - kf6-kglobalaccel-dev
      - kf6-kguiaddons-dev
      - kf6-ki18n-dev
      - kf6-kwidgetsaddons-dev
      - libglvnd-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtshadertools-dev
      - qt6-qttools-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8b2dcf76e3f56bf5ea5cfaae83afa494bbad29af
      repository: https://invent.kde.org/frameworks/kdeclarative
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

