package:
  name: kf6-prison
  version: "6.18.0"
  epoch: 0
  description: prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
  copyright:
    - license: BSD-3-Clause AND CC0-1.0 AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - libqrencode-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtmultimedia-dev
      - qt6-qttools-dev
      - vulkan-headers
      - zxing-cpp-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 086f24bf50e97f809179ede1e598d36d6fcb20fe
      repository: https://invent.kde.org/frameworks/prison
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

