package:
  name: kf6-kidletime
  version: "6.18.0"
  epoch: 0
  description: KIdleTime
  copyright:
    - license: C0-1.0 AND GPL-2.0-or-later AND LGPL-2.1-or-later AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - plasma-wayland-protocols-dev
      - qt6-qtbase-dev
      - qt6-qtwayland-dev
      - vulkan-headers
      - wayland-dev
      - wayland-protocols

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 84bff4abd55f2a9285be29a77a5654e3678fb56b
      repository: https://invent.kde.org/frameworks/kidletime
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/ \
        -DWITH_X11=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

