package:
  name: kglobalacceld
  version: "6.4.90"
  epoch: 0
  description: Daemon providing Global Keyboard Shortcut (Accelerator) functionality
  copyright:
    - license: CC0-1.0 AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND (LGPL-2.1-only OR LGPL-3.0-only)

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-kbookmarks-dev
      - kf6-kcompletion-dev
      - kf6-kconfig-dev
      - kf6-kcoreaddons-dev
      - kf6-kcrash-dev
      - kf6-kdbusaddons-dev
      - kf6-kglobalaccel-dev
      - kf6-kio-dev
      - kf6-kitemviews-dev
      - kf6-kjobwidgets-dev
      - kf6-kservice-dev
      - kf6-kwidgetsaddons-dev
      - kf6-kwindowsystem-dev
      - kf6-solid-dev
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0e67c8a924e4e3bb8f90e0d1f29bd4ed54c1ccc7
      repository: https://invent.kde.org/plasma/kglobalacceld
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCM_DIR=/usr/share/ECM/ \
        -DWITH_X11=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

