package:
  name: knighttime
  version: "6.4.90"
  epoch: 0
  description: Helpers for scheduling the dark-light cycle
  copyright:
    - license: BSD-3-Clause AND LGPL-2.0-or-later AND LicenseRef-KDE-Accepted-LGPL AND CC0-1.0 AND LGPL-2.1-only AND LicenseRef-Qt-Commercial AND GPL-2.0-only AND LGPL-2.1-or-later AND Qt-LGPL-exception-1.1 GPL-2.0-or-later  LGPL-3.0-only GPL-3.0-only LicenseRef-KDE-Accepted-GPL

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - kf6-kconfig-dev
      - kf6-kcoreaddons-dev
      - kf6-kdbusaddons-dev
      - kf6-kholidays-dev
      - kf6-ki18n-dev
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtpositioning-dev
      - qt6-qttools-dev
      - vulkan-headers
      - vulkan-loader
      # TODO: complaint about Qt6QmlCompilerPlusPrivateTools

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 587994c4951133ce678893dd5e78c813f41cd677
      repository: https://invent.kde.org/plasma/knighttime
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

