package:
  name: kwayland
  version: "6.4.90"
  epoch: 0
  description: KWayland provides a Qt-style Client and Server library wrapper for the Wayland libraries.
  copyright:
    - license: BSD-3-Clause AND CC0-1.0 AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND MIT-CMU AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - libxkbcommon-dev
      - plasma-wayland-protocols-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtwayland-dev
      - vulkan-headers
      - wayland-dev
      - wayland-protocols


pipeline:
  - uses: git-checkout
    with:
      expected-commit: a7f4f4428c4379ddbba7df977907b89c7ca7ed57
      repository: https://invent.kde.org/plasma/kwayland
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

