package:
  name: layer-shell-qt
  version: "6.4.90"
  epoch: 0
  description: Qt component to allow applications to make use of the Wayland wl-layer-shell protocol.
  copyright:
    - license: BSD-3-Clause AND CC0-1.0 AND LGPL-3.0-or-later AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtwayland-dev
      - vulkan-headers
      - wayland-dev
      - wayland-protocols

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ebd64dd395aa91eef21716b9840a2fd72a6b246f
      repository: https://invent.kde.org/plasma/layer-shell-qt
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

