package:
  name: libkscreen
  version: "6.4.90"
  epoch: 0
  description: KDE's screen management software
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - libglvnd-dev
      - libxcb-dev
      - libxkbcommon-dev
      - plasma-wayland-protocols-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qttools-dev
      - qt6-qtwayland-dev
      - vulkan-headers
      - wayland-dev


pipeline:
  - uses: git-checkout
    with:
      expected-commit: 21c96a3c7c8009923792986f2c9467e6b2d6b3c1
      repository: https://invent.kde.org/plasma/libkscreen
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - runs: |
        kwin --version

