package:
  name: libwnck
  version: 43.3
  epoch: 0
  description: Window Navigator Construction Kit
  copyright:
    - license: LicenseRef-Callaway-LGPLv2+

environment:
  contents:
    packages:
      - apk-tools
      - build-base
      - busybox
      - glib-dev
      - gtk-3-dev
      - glib-gir
      - startup-notification-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.gnome.org/GNOME/libwnck
      tag: ${{package.version}}
      expected-commit: 75e56cf1d7ef1edd61516bdf25bf7fdee8b935f3

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11006

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
