package:
  name: minizip-ng
  version: "4.0.10"
  epoch: 0
  description: assimp
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - openssl-dev
      - zlib-dev
      - bzip2-dev
      - xz-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zlib-ng/minizip-ng
      tag: ${{package.version}}
      expected-commit: f3ed731e27a97e30dffe076ed5e0537daae5c1bd

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: zlib-ng/minizip-ng
    use-tag: true

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf
