package:
  name: phonon
  version: "4.12.0"
  epoch: 0
  description: Multi-platform sound framework for application developers
  copyright:
    - license: LicenseRef-Callaway-LGPLv2+

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - glib-dev
      - libglvnd-dev
      - pulseaudio-dev
      - qt6-qt5compat-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qttools-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fcf587a6a59ea4d54104635c903c1999751ee923
      repository: https://invent.kde.org/libraries/phonon
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/ \
        -DPHONON_BUILD_QT5=OFF \
        -DPHONON_BUILD_QT6=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

