package:
  name: plasma-wayland-protocols
  version: "1.19.0"
  epoch: 0
  description: Plasma-specific protocols for Wayland
  copyright:
    - license: BSD-3-Clause AND CC0-1.0 AND LGPL-2.1-or-later AND MIT-CMU

environment:
  contents:
    packages:
      - build-base
      - busybox
      - extra-cmake-modules
      - wayland-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3b201c79e8172a3060d4b31a6d69ce37bb9cde71
      repository: https://invent.kde.org/libraries/plasma-wayland-protocols
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_DIR=/usr/share/ECM/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check

