package:
  name: py3-pyside6
  version: "6.9.1"
  epoch: 0
  description: pyside6
  copyright:
    - license: LGPL-3.0-or-later

vars:
  llvm-vers: 20

environment:
  contents:
    packages:
      # - qt6-qtwebengine-dev
      - build-base
      - busybox
      - clang-${{vars.llvm-vers}}
      - clang-${{vars.llvm-vers}}-extras
      - cmake
      - cups-dev
      - graphviz
      - libglvnd-dev
      - libxkbcommon-dev
      - libxslt-dev
      - llvm-${{vars.llvm-vers}}
      - llvm-${{vars.llvm-vers}}-dev
      - ninja
      - py3-clang-${{vars.llvm-vers}}
      - py3-libclang
      - py3-numpy
      - py3-sphinx
      - py3-supported-numpy
      - py3-supported-python
      - python3-dev
      - qt6-qt3d-dev
      - qt6-qtbase-dev
      - qt6-qtcharts-dev
      - qt6-qtconnectivity-dev
      - qt6-qtdatavis3d-dev
      - qt6-qtdeclarative-dev
      - qt6-qtgraphs-dev
      - qt6-qthttpserver-dev
      - qt6-qtlocation-dev
      - qt6-qtmultimedia-dev
      - qt6-qtnetworkauth-dev
      - qt6-qtpositioning-dev
      - qt6-qtquick3d-dev
      - qt6-qtremoteobjects-dev
      - qt6-qtscxml-dev
      - qt6-qtsensors-dev
      - qt6-qtserialbus-dev
      - qt6-qtserialport-dev
      - qt6-qtspeech-dev
      - qt6-qtsvg-dev
      - qt6-qttools-dev
      - qt6-qtwebchannel-dev
      - qt6-qtwebsockets-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pyside/pyside-setup
      tag: v${{package.version}}
      expected-commit: a6b4e21e4aff922e13948a0f546471a5e37a440e

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_PREFIX_PATH="/usr/lib/llvm-${{vars.llvm-vers}}/lib/cmake/"

  - uses: cmake/build

  - uses: cmake/install

#  - runs: |
#      ln -s /usr/lib/llvm-19/lib/LLVMgold.so /usr/lib/ # I cannot convince ld to find this here
#      # Needed to find our llvm libs
#      export CXXFLAGS="$CXXFLAGS -I/usr/lib/llvm-${{vars.llvm-vers}}/include"
#      export CC=clang
#      export CXX=clang++
#
#      cmake -B build -G Ninja -Wno-dev \
#        -DCMAKE_INSTALL_PREFIX=/usr \
#        -DCMAKE_INSTALL_LIBDIR=lib \
#        -DCMAKE_BUILD_TYPE=Release \
#        -DCMAKE_VERBOSE_MAKEFILE=ON \
#        -DClang_DIR=/usr/lib/llvm-19/lib/cmake/clang
#
#      cmake --build build
#      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

update:
  enabled: true
  github:
    identifier: pyside/pyside-setup
    use-tag: true
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf
