package:
  name: qcoro
  version: "0.12.0"
  epoch: 0
  description: C++ Coroutines for Qt 
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - qt6-qtdeclarative-dev
      - qt6-qtwebsockets-dev
      - vulkan-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ef1231ae490465b4f592ca326eee6d56a3d802ae
      repository: https://github.com/qcoro/qcoro
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt6/mkspecs/modules \
        -DUSE_QT_VERSION=6 \
        -DBUILD_TESTING=ON \
        -DQCORO_BUILD_EXAMPLES=ON \
        -DQCORO_ENABLE_ASAN=OFF \
        -DQCORO_WITH_QML=ON \
        -DQCORO_WITH_QTDBUS=ON \
        -DQCORO_WITH_QTNETWORK=ON \
        -DQCORO_WITH_QTQUICK=ON \
        -DQCORO_WITH_QTWEBSOCKETS=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
