package:
  name: qt6-qtwayland
  version: "6.10.0"
  epoch: 0
  description: qtwayland
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libglvnd-dev
      - libxkbcommon-dev
      - qt6-qtbase-dev
      - vulkan-headers
      - vulkan-loader
      - wayland-dev

var-transforms:
  - from: ${{package.version}}
    match: "_"
    replace: "-"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/qt/qtwayland
      tag: v${{vars.mangled-package-version}}
      expected-commit: 4a35a78b817112a212779c4edcc247b166971017

  - uses: qt6/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: qt/qtwayland
    use-tag: true
    strip-prefix: v
  ignore-regex-patterns:
    - 'rc\d+$'
    - 'beta\d+$'

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf
