package:
  name: openxr
  version: "1.1.51"
  epoch: 0
  description: Generated headers and sources for OpenXR loader. 
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - jsoncpp-dev
      - jsoncpp-static
      - libglvnd-dev
      - python3-dev
      - vulkan-headers
      - vulkan-loader
      - xorg-server-dev
      #- wayland-dev
      - extra-cmake-modules

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/KhronosGroup/OpenXR-SDK
      tag: release-${{package.version}}
      expected-commit: e595991c05b9053cfc8073f308be6571c25ffe47
      recurse-submodules: true

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: KhronosGroup/OpenXR-SDK
    use-tag: true
    strip-prefix: v
  ignore-regex-patterns:
    - 'rc\d+$'
    - 'beta\d+$'

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf

