package:
  name: switcheroo-control
  version: "3.0"
  epoch: 0
  description: 
  copyright:
    - license: GNU GPLv3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - glib-dev
      - libgudev-dev
      - libdrm-dev
      - python3-dev
      - gtk-doc


pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/hadess/switcheroo-control
      expected-commit: 2adfa2dff85b9886ce0fddca6863fe9f2eaf54a0
      tag: ${{package.version}}

  - uses: meson/configure
    with:
      opts: |
        -Dgtk_doc=true

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 12350

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
