name: Build Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Check Just Syntax
        uses: ublue-os/just-action@205c35468e90e4973e79ca37597be9cf242a5760

      - name: Build Packages with melange
        uses: addnab/docker-run-action@v3
        with:
          image: cgr.dev/chainguard/wolfi-base
          options: --privileged -v ${{ github.workspace }}:/workspace
          run: |
            apk update && apk add melange just
            cd /workspace
            melange keygen
            just qt 2>&1 | rg -i -C 10 'WARN|ERRO'


